### PR TITLE
Several fixes and improvements:

### PR DESCRIPTION
**Pull request by ghost**
- set "CreatedBySpell" to "Call Pet" (883) instead of 0 (fix pet resummon after e.g. dismount)
- create tamed pet directly (it is not necessary to spawn the creature, copy it for taming and kill it afterwards)
- new config parameter "BeastMaster.KeepPetHappy"; if true always sets the happiness to maximum if the pet attacks (accomplished using UnitScript)
- added extra if-clause to check if the player is a hunter before granting the hunter spells

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Hmm, I wish someone could test it before merging. Please, be (very) patient, but it's appreciated!

**Comment by Stoabrogga** [comment]
Added one more fix

**Comment by dunjeon** [comment]
Tested, and it is working

**Comment by BarbzYHOOL** [comment]
Thank you @dunjeon , so let's merge it!

**Pull request merged**
