### PR TITLE
allow pet lists to be configured; clean up bugged pets 

### PR DESCRIPTION
**Pull request by Stoabrogga**
Pets can now be specified in the config file without touching the code. I also cleaned up a few of the bugged pets, for example the Bat or the Dragonhawk, and updated their IDs.

Tested build on Ubuntu 16.04 and in-game.

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
oh shit i forgot to merge this and now it's conflicting @Stoabrogga @StygianTheBest

**Comment by BarbzYHOOL** [comment]
oh shit i forgot to merge this and now it's conflicting @Stoabrogga @StygianTheBest

**Comment by BarbzYHOOL** [comment]
oh shit i forgot to merge this and now it's conflicting @Stoabrogga @StygianTheBest

**Comment by Stoabrogga** [comment]
I'll stick to my own fork, this is not compatible anymore.

**Comment by BarbzYHOOL** [comment]
We'll sort this out soon

**Pull request merged**
