### PR TITLE
Feat(DB/SAI): Use new cmake macros; update texts & model; take over preferences, templates etc. from skeleton-module

### PR DESCRIPTION
**Pull request by Stoabrogga**
- Use new cmake macros
- Update texts in order to give the player a clue what this NPC is all about
- Update the model to the Northrend White Worgen
- take over preferences, templates, scripts etc. from the skeleton module
- Allow config reloading in order to dynamically change the pet lists

Tested build and in-game under Ubuntu 16.04

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@dunjeon
Could you please test this PR on occasion?

**Comment by dunjeon** [comment]
@Stoabrogga Sure thing!

**Comment by Stoabrogga** [comment]
@dunjeon
Great, thanks. Don't forget to apply the SQL script.

**Comment by dunjeon** [comment]
@Stoabrogga I'll be able to do this tomorrow. =)

**Comment by Stoabrogga** [comment]
@dunjeon 
No hurry, thanks :+1:

**Comment by dunjeon** [comment]
@Stoabrogga
Merged, compiled, SQL applied without error.  Currently running live on my test server.  Nice Job! Thanks for your effort =)

**Comment by Stoabrogga** [comment]
Merged. Thanks for testing and your feedback @dunjeon

**Pull request merged**
